// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/internal_application.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Com.Samples.V1 {
  public static partial class InternalApplicationService
  {
    static readonly string __ServiceName = "com.samples.InternalApplicationService";

    static readonly grpc::Marshaller<global::Com.Samples.V1.ApplicationStatusRequest> __Marshaller_ApplicationStatusRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Samples.V1.ApplicationStatusRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Com.Samples.V1.ApplicationStatusResponse> __Marshaller_ApplicationStatusResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Samples.V1.ApplicationStatusResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Com.Samples.V1.ApplicationStatusRequest, global::Com.Samples.V1.ApplicationStatusResponse> __Method_GetApplicationStatus = new grpc::Method<global::Com.Samples.V1.ApplicationStatusRequest, global::Com.Samples.V1.ApplicationStatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetApplicationStatus",
        __Marshaller_ApplicationStatusRequest,
        __Marshaller_ApplicationStatusResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Samples.V1.InternalApplicationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InternalApplicationService</summary>
    public abstract partial class InternalApplicationServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Com.Samples.V1.ApplicationStatusResponse> GetApplicationStatus(global::Com.Samples.V1.ApplicationStatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InternalApplicationService</summary>
    public partial class InternalApplicationServiceClient : grpc::ClientBase<InternalApplicationServiceClient>
    {
      /// <summary>Creates a new client for InternalApplicationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public InternalApplicationServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InternalApplicationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public InternalApplicationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected InternalApplicationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected InternalApplicationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Com.Samples.V1.ApplicationStatusResponse GetApplicationStatus(global::Com.Samples.V1.ApplicationStatusRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetApplicationStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Com.Samples.V1.ApplicationStatusResponse GetApplicationStatus(global::Com.Samples.V1.ApplicationStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetApplicationStatus, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Samples.V1.ApplicationStatusResponse> GetApplicationStatusAsync(global::Com.Samples.V1.ApplicationStatusRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetApplicationStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Samples.V1.ApplicationStatusResponse> GetApplicationStatusAsync(global::Com.Samples.V1.ApplicationStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetApplicationStatus, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override InternalApplicationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InternalApplicationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(InternalApplicationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetApplicationStatus, serviceImpl.GetApplicationStatus).Build();
    }

  }
}
#endregion
